L
-- くまっちパズル: ランキング用テーブル
-- Supabaseダッシュボードの「SQL Editor」にこの内容を貼り付けて実行してください。
 
create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 12),
  score integer not null check (score >= 0),
  level integer not null default 1 check (level >= 1),
  mode text not null default 'solo' check (mode in ('solo', 'battle')),
  created_at timestamptz not null default now()
);
 
-- 検索を速くするためのインデックス(スコア降順で上位を取るため)
create index if not exists scores_mode_score_idx on public.scores (mode, score desc);
 
-- Row Level Security を有効化
alter table public.scores enable row level security;
 
-- 誰でもランキングを閲覧できる
drop policy if exists "Anyone can read scores" on public.scores;
create policy "Anyone can read scores"
  on public.scores
  for select
  using (true);
 
-- 誰でもスコアを登録できる(匿名投稿を許可)
drop policy if exists "Anyone can insert scores" on public.scores;
create policy "Anyone can insert scores"
  on public.scores
  for insert
  with check (true);
 
-- 重要: RLSポリシーだけでなく、テーブルへの基本権限(GRANT)も必要
-- SQL Editorから直接テーブルを作った場合、anon/authenticatedロールに
-- 権限が自動付与されないことがあり、これが「登録できない」原因になりやすい
grant usage on schema public to anon, authenticated;
grant select, insert on public.scores to anon, authenticated;
 
-- 追加カラム: AI対戦の「勝利までの秒数」ランキング用、ソロプレイの「プレイ時間」表示用
alter table public.scores add column if not exists duration_seconds integer;
alter table public.scores add column if not exists difficulty text check (difficulty in ('easy','normal','hard','master'));
 
-- AI対戦ランキング(難易度別・タイム昇順)を速くするための部分インデックス
create index if not exists scores_battle_diff_duration_idx
  on public.scores (mode, difficulty, duration_seconds asc)
  where mode = 'battle';
 
-- 同じ名前の重複を防ぐため、自己ベストの更新(UPDATE)を許可する
-- (削除は行わず、既存の行を上書きする方式。一覧側は名前ごとの最良の1件だけを表示する)
drop policy if exists "Anyone can update scores" on public.scores;
create policy "Anyone can update scores"
  on public.scores
  for update
  using (true)
  with check (true);
 
grant update on public.scores to anon, authenticated;
 
-- 安全装置: 記録が「悪化」する更新(ソロ=スコアが下がる、AI対戦=タイムが遅くなる)を
-- データベース側でも拒否する(クライアントのバグや不正な直接アクセスからも保護する)
create or replace function public.prevent_score_regression()
returns trigger
language plpgsql
as $$
begin
  if new.mode = 'solo' and new.score < old.score then
    raise exception 'new score (%) must be higher than existing best (%)', new.score, old.score;
  end if;
  if new.mode = 'battle' and old.duration_seconds is not null
     and new.duration_seconds is not null
     and new.duration_seconds > old.duration_seconds then
    raise exception 'new time (%) must be faster than existing best (%)', new.duration_seconds, old.duration_seconds;
  end if;
  return new;
end;
$$;
 
drop trigger if exists trg_prevent_score_regression on public.scores;
create trigger trg_prevent_score_regression
  before update on public.scores
  for each row execute function public.prevent_score_regression();
 
-- 削除はクライアントから一切許可しない(ポリシーを作らないことで自動的に拒否されます)
 
-- ==========================================================
-- オンライン対戦: ランダムマッチング用の待合キュー
-- 実際の対戦中の通信(盤面同期・おじゃま送信など)はSupabase Realtimeの
-- Broadcast/Presenceチャンネルを使うため、テーブルには一切保存しない。
-- このテーブルは「対戦相手を探す」フェーズだけで使う一時的なキュー。
-- ==========================================================
create table if not exists public.matchmaking_queue (
  id bigint generated by default as identity primary key,
  client_id text not null unique,
  nickname text,
  status text not null default 'waiting' check (status in ('waiting', 'matched')),
  room_code text,
  created_at timestamptz not null default now()
);
 
-- RLSを有効化した上でポリシーは一切作らない
-- (クライアントからテーブルへの直接アクセスは常に拒否し、
--  下のfind_or_create_match関数経由でのみ安全に読み書きさせる)
alter table public.matchmaking_queue enable row level security;
 
-- ランダムマッチングの中核ロジック。呼び出すたびに:
--   1. 古い待機行(30秒以上前)や古いマッチ済み行(2分以上前)を掃除する
--   2. 自分が既に他の誰かとマッチ済みならそのroom_codeを返す
--   3. 他に待機中のプレイヤーがいればペアにしてroom_codeを発行する
--   4. 誰もいなければ自分を待機列に入れて matched=false を返す
-- security definer + テーブル所有者権限により、RLSを迂回して安全にテーブルへアクセスする
-- (呼び出し元のクライアントは直接テーブルを読み書きできない)
create or replace function public.find_or_create_match(p_client_id text, p_nickname text)
returns table(room_code text, matched boolean)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_partner record;
  v_room text;
begin
  delete from public.matchmaking_queue
    where status = 'waiting' and created_at < now() - interval '30 seconds';
  delete from public.matchmaking_queue
    where status = 'matched' and created_at < now() - interval '2 minutes';
 
  -- 既に自分がマッチ済みなら、そのroom_codeをそのまま返す
  select * into v_partner from public.matchmaking_queue where client_id = p_client_id and status = 'matched';
  if found then
    return query select v_partner.room_code, true;
    return;
  end if;
 
  -- 自分以外で待機中の最も古いプレイヤーを探してロックする(同時マッチングの競合を防ぐ)
  select * into v_partner
    from public.matchmaking_queue
    where status = 'waiting' and client_id <> p_client_id
    order by created_at asc
    limit 1
    for update skip locked;
 
  if found then
    v_room := substr(md5(random()::text || clock_timestamp()::text), 1, 10);
    update public.matchmaking_queue set status = 'matched', room_code = v_room where id = v_partner.id;
    insert into public.matchmaking_queue (client_id, nickname, status, room_code)
      values (p_client_id, p_nickname, 'matched', v_room)
      on conflict (client_id) do update
        set status = 'matched', room_code = v_room, nickname = excluded.nickname, created_at = now();
    return query select v_room, true;
    return;
  end if;
 
  -- 待機中の相手がいなければ、自分を待機列に入れる(既に行があれば更新)
  insert into public.matchmaking_queue (client_id, nickname, status, room_code)
    values (p_client_id, p_nickname, 'waiting', null)
    on conflict (client_id) do update
      set status = 'waiting', room_code = null, nickname = excluded.nickname, created_at = now();
 
  return query select null::text, false;
end;
$$;
 
-- 「対戦相手を探す」をキャンセルした時に、自分の待機行だけを消す
create or replace function public.leave_matchmaking(p_client_id text)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.matchmaking_queue where client_id = p_client_id and status = 'waiting';
$$;
 
grant execute on function public.find_or_create_match(text, text) to anon, authenticated;
grant execute on function public.leave_matchmaking(text) to anon, authenticated;
